[project]
name = "ai-guardrails-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hcdangan", email = "hcdangan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic-ai",
    "guardrails-ai",
]

[project.scripts]
ai-guardrails-tutorial = "ai_guardrails_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
